"""Add reset_token fields to User model

Revision ID: f1b750b422a6
Revises: 
Create Date: 2024-08-01 11:50:10.996660

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f1b750b422a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('reset_token', sa.String(length=36), nullable=True))
    op.add_column('user', sa.Column('reset_token_expires_at', sa.DateTime(), nullable=True))
    op.alter_column('user', 'first_name',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=120),
               existing_nullable=False)
    op.alter_column('user', 'last_name',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=120),
               existing_nullable=False)
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.alter_column('user', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'USER', name='userrole'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'USER', name='userrole'),
               nullable=False)
    op.alter_column('user', 'password',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('user', 'last_name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
    op.alter_column('user', 'first_name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
    op.drop_column('user', 'reset_token_expires_at')
    op.drop_column('user', 'reset_token')
    # ### end Alembic commands ###
